#!/bin/sh
cmm=$1;shift;
if [ $# -eq 0 ]; then
list=*.edp
elif  [ $# -gt  0 ]; then
list="$@"
fi
for i in $list
do
    case $i in
	all.edp|regtests.edp) 
	    echo  pass   $i;; 
	*)
	    ( $cmm "$i" )2>&1 1>$i-out;
	    if [ $? -eq 0 ] 
	    then 
		echo  OK $cmm $i;
	    else  
		echo  FAIL $cmm $i "( see $i-out )";
		echo  FAIL $cmm $i "(see $i-out ">>/tmp/list-ff-$$
	    fi
	    ;;
    esac
done