#!/bin/bash
if [ "$1" != "www" -a "$1" != "doc" ]; then
   echo "usage : $0 www    or $0 doc "
   exit 
fi
VERSION=`awk '/#define VersionFreeFempp/ {print $3}' config-version.h`
listf=(freefem++-${VERSION}.tar.gz FreeFem++v${VERSION}_MacOsX.tgz FreeFem++v${VERSION}_Win.zip  FreeFem++v${VERSION}_MacOS.sit)
listcd=(freefem++.tar.gz           "freefem++_macosx.tgz"          freefem++.zip                 freefem++.sit)

www=hecht@rascasse.inria.fr:www_gamma/Gamma/cdrom/ftp/freefem/
ftp=hecht@rascasse.inria.fr:/ftp_gamma/freefem/
ftpk=hecht@baobab.ann.jussieu.fr:public_html/ftp/freefem/

if [ -f Output/FreeFem++-$VERSION.exe ]; then
  scp Output/FreeFem++-${VERSION}.exe  $ftpk
  scp Output/FreeFem++-${VERSION}.exe  $ftp
  scp Output/FreeFem++-${VERSION}.exe  $www/freefem.exe
else
list1="HISTORY DOC/manual-full.pdf DOC/manual-full.ps.gz"


if [ "$1" = "doc"  ]; then
 set -x 
 rsync -vzupogt --rsh="ssh -l hecht" $list1  $ftpk
 rsync -vzupogt --rsh="ssh -l hecht"  HISTORY  baobab.ann.jussieu.fr:www/.
 scp HISTORY hecht@rascasse.inria.fr:www_gamma/Gamma/cdrom/www/freefem/
fi
if [ "$1" = "www"  ]; then
for ((i=0;${#listf[$i]};i++)); do
f=${listf[$i]}
lcd=${listcd[$i]}
echo file : $f 
if [ -f $f ]; then
    rsync -vzupogt --rsh="ssh -l hecht" $f  $ftpk
    scp $f $ftp
    if [ -n "$lcd" ] ; then
      scp $f $www$lcd
    fi

fi
done;
fi
fi
echo ssh  hecht@baobab.ann.jussieu.fr "cd www/.; ./.update++ ${VERSION} <ff++.htmx >freefem++.htm"
ssh  hecht@baobab.ann.jussieu.fr "cd www/.; ./.update++ ${VERSION} <ff++.htmx >freefem++.htm"
# ssh rascasse.inria.fr "cd ~/public_html/; ./.update++ ${VERSION} <ff++.htmx >freefem++.htm"
