#!/bin/sh
# clean old mpi and fortran 
cd / 
rm ./usr/local/bin/gfortran
rm ./usr/local/bin/mpic++
rm ./usr/local/bin/mpic++-vt
rm ./usr/local/bin/mpicc
rm ./usr/local/bin/mpicc-vt
rm ./usr/local/bin/mpicxx
rm ./usr/local/bin/mpicxx-vt
rm ./usr/local/bin/mpiexec
rm ./usr/local/bin/mpif77
rm ./usr/local/bin/mpif77-vt
rm ./usr/local/bin/mpif90
rm ./usr/local/bin/mpif90-vt
rm ./usr/local/bin/mpirun
rm ./usr/local/bin/ompi-clean
rm ./usr/local/bin/ompi-iof
rm ./usr/local/bin/ompi-probe
rm ./usr/local/bin/ompi-profiler
rm ./usr/local/bin/ompi-ps
rm ./usr/local/bin/ompi-server
rm ./usr/local/bin/ompi-top
rm ./usr/local/bin/ompi_info
rm ./usr/local/bin/opal_wrapper
rm ./usr/local/bin/orte-bootproxy.sh
rm ./usr/local/bin/orte-clean
rm ./usr/local/bin/orte-iof
rm ./usr/local/bin/orte-ps
rm ./usr/local/bin/orte-top
rm ./usr/local/bin/orte_wrapper_script
rm ./usr/local/bin/ortec++
rm ./usr/local/bin/ortecc
rm ./usr/local/bin/orted
rm ./usr/local/bin/orterun
rm ./usr/local/bin/otfaux
rm ./usr/local/bin/otfcompress
rm ./usr/local/bin/otfconfig
rm ./usr/local/bin/otfdecompress
rm ./usr/local/bin/otfinfo
rm ./usr/local/bin/otfmerge
rm ./usr/local/bin/otfmerge-mpi
rm ./usr/local/bin/otfprint
rm ./usr/local/bin/otfprofile
rm ./usr/local/bin/otfprofile-mpi
rm ./usr/local/bin/otfshrink
rm ./usr/local/bin/vtc++
rm ./usr/local/bin/vtcc
rm ./usr/local/bin/vtcxx
rm ./usr/local/bin/vtf77
rm ./usr/local/bin/vtf90
rm ./usr/local/bin/vtfilter
rm ./usr/local/bin/vtfilter-mpi
rm ./usr/local/bin/vtfiltergen
rm ./usr/local/bin/vtfiltergen-mpi
rm ./usr/local/bin/vtfort
rm ./usr/local/bin/vtrun
rm ./usr/local/bin/vtsetup
rm ./usr/local/bin/vtsetup.jar
rm ./usr/local/bin/vtunify
rm ./usr/local/bin/vtunify-mpi
rm ./usr/local/bin/vtwrapper
rm ./usr/local/etc/openmpi-default-hostfile
rm ./usr/local/etc/openmpi-mca-params.conf
rm ./usr/local/etc/openmpi-totalview.tcl
rm ./usr/local/etc/vtsetup-config.dtd
rm ./usr/local/etc/vtsetup-config.xml
rm -rf  ./usr/local/include/c++/4.9.0
rm ./usr/local/include/gmp.h
rm ./usr/local/include/mpc.h
rm ./usr/local/include/mpf2mpfr.h
rm ./usr/local/include/mpfr.h
rm ./usr/local/include/mpi-ext.h
rm ./usr/local/include/mpi.h
rm ./usr/local/include/mpi_portable_platform.h
rm ./usr/local/include/mpif-common.h
rm ./usr/local/include/mpif-config.h
rm ./usr/local/include/mpif-mpi-io.h
rm ./usr/local/include/mpif.h
rm -rf ./usr/local/include/openmpi
rm -rf ./usr/local/include/vampirtrace
rm -rf ./usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.9.0
rm ./usr/local/lib/i386/libasan.0.dylib
rm ./usr/local/lib/i386/libasan.dylib
rm ./usr/local/lib/i386/libasan.la
rm ./usr/local/lib/i386/libasan_preinit.o
rm ./usr/local/lib/i386/libatomic.1.dylib
rm ./usr/local/lib/i386/libatomic.a
rm ./usr/local/lib/i386/libatomic.dylib
rm ./usr/local/lib/i386/libatomic.la
rm ./usr/local/lib/i386/libgfortran.3.dylib
rm ./usr/local/lib/i386/libgfortran.a
rm ./usr/local/lib/i386/libgfortran.dylib
rm ./usr/local/lib/i386/libgfortran.la
rm ./usr/local/lib/i386/libgfortran.spec
rm ./usr/local/lib/i386/libgomp.1.dylib
rm ./usr/local/lib/i386/libgomp.a
rm ./usr/local/lib/i386/libgomp.dylib
rm ./usr/local/lib/i386/libgomp.la
rm ./usr/local/lib/i386/libgomp.spec
rm ./usr/local/lib/i386/libitm.1.dylib
rm ./usr/local/lib/i386/libitm.a
rm ./usr/local/lib/i386/libitm.dylib
rm ./usr/local/lib/i386/libitm.la
rm ./usr/local/lib/i386/libitm.spec
rm ./usr/local/lib/i386/libquadmath.0.dylib
rm ./usr/local/lib/i386/libquadmath.a
rm ./usr/local/lib/i386/libquadmath.dylib
rm ./usr/local/lib/i386/libquadmath.la
rm ./usr/local/lib/i386/libssp.0.dylib
rm ./usr/local/lib/i386/libssp.a
rm ./usr/local/lib/i386/libssp.dylib
rm ./usr/local/lib/i386/libssp.la
rm ./usr/local/lib/i386/libssp_nonshared.a
rm ./usr/local/lib/i386/libssp_nonshared.la
rm ./usr/local/lib/i386/libstdc++.6.dylib
rm ./usr/local/lib/i386/libstdc++.a
rm ./usr/local/lib/i386/libstdc++.a-gdb.py
rm ./usr/local/lib/i386/libstdc++.dylib
rm ./usr/local/lib/i386/libstdc++.la
rm ./usr/local/lib/i386/libsupc++.a
rm ./usr/local/lib/i386/libsupc++.la
rm ./usr/local/lib/i386/libubsan.0.dylib
rm ./usr/local/lib/i386/libubsan.dylib
rm ./usr/local/lib/i386/libubsan.la
rm ./usr/local/lib/libasan.0.dylib
rm ./usr/local/lib/libasan.dylib
rm ./usr/local/lib/libasan.la
rm ./usr/local/lib/libasan_preinit.o
rm ./usr/local/lib/libatomic.1.dylib
rm ./usr/local/lib/libatomic.a
rm ./usr/local/lib/libatomic.dylib
rm ./usr/local/lib/libatomic.la
rm ./usr/local/lib/libgcc_ext.10.4.dylib
rm ./usr/local/lib/libgcc_ext.10.5.dylib
rm ./usr/local/lib/libgcc_s.1.dylib
rm ./usr/local/lib/libgcc_s_ppc64.1.dylib
rm ./usr/local/lib/libgcc_s_x86_64.1.dylib
rm ./usr/local/lib/libgfortran.3.dylib
rm ./usr/local/lib/libgfortran.a
rm ./usr/local/lib/libgfortran.dylib
rm ./usr/local/lib/libgfortran.la
rm ./usr/local/lib/libgfortran.spec
rm ./usr/local/lib/libgmp.a
rm ./usr/local/lib/libgmp.la
rm ./usr/local/lib/libgomp.1.dylib
rm ./usr/local/lib/libgomp.a
rm ./usr/local/lib/libgomp.dylib
rm ./usr/local/lib/libgomp.la
rm ./usr/local/lib/libgomp.spec
rm ./usr/local/lib/libiberty.a
rm ./usr/local/lib/libitm.1.dylib
rm ./usr/local/lib/libitm.a
rm ./usr/local/lib/libitm.dylib
rm ./usr/local/lib/libitm.la
rm ./usr/local/lib/libitm.spec
rm ./usr/local/lib/libmca_common_sm.3.dylib
rm ./usr/local/lib/libmca_common_sm.dylib
rm ./usr/local/lib/libmca_common_sm.la
rm ./usr/local/lib/libmpc.a
rm ./usr/local/lib/libmpc.la
rm ./usr/local/lib/libmpfr.a
rm ./usr/local/lib/libmpfr.la
rm ./usr/local/lib/libmpi.1.dylib
rm ./usr/local/lib/libmpi.dylib
rm ./usr/local/lib/libmpi.la
rm ./usr/local/lib/libmpi_cxx.1.dylib
rm ./usr/local/lib/libmpi_cxx.dylib
rm ./usr/local/lib/libmpi_cxx.la
rm ./usr/local/lib/libmpi_f77.1.dylib
rm ./usr/local/lib/libmpi_f77.dylib
rm ./usr/local/lib/libmpi_f77.la
rm ./usr/local/lib/libmpi_f90.a
rm ./usr/local/lib/libmpi_f90.la
rm ./usr/local/lib/libompitrace.0.dylib
rm ./usr/local/lib/libompitrace.dylib
rm ./usr/local/lib/libompitrace.la
rm ./usr/local/lib/libopen-pal.4.dylib
rm ./usr/local/lib/libopen-pal.dylib
rm ./usr/local/lib/libopen-pal.la
rm ./usr/local/lib/libopen-rte.4.dylib
rm ./usr/local/lib/libopen-rte.dylib
rm ./usr/local/lib/libopen-rte.la
rm ./usr/local/lib/libopen-trace-format.1.dylib
rm ./usr/local/lib/libopen-trace-format.a
rm ./usr/local/lib/libopen-trace-format.dylib
rm ./usr/local/lib/libopen-trace-format.la
rm ./usr/local/lib/libotfaux.0.dylib
rm ./usr/local/lib/libotfaux.a
rm ./usr/local/lib/libotfaux.dylib
rm ./usr/local/lib/libotfaux.la
rm ./usr/local/lib/libquadmath.0.dylib
rm ./usr/local/lib/libquadmath.a
rm ./usr/local/lib/libquadmath.dylib
rm ./usr/local/lib/libquadmath.la
rm ./usr/local/lib/libssp.0.dylib
rm ./usr/local/lib/libssp.a
rm ./usr/local/lib/libssp.dylib
rm ./usr/local/lib/libssp.la
rm ./usr/local/lib/libssp_nonshared.a
rm ./usr/local/lib/libssp_nonshared.la
rm ./usr/local/lib/libstdc++.6.dylib
rm ./usr/local/lib/libstdc++.a
rm ./usr/local/lib/libstdc++.a-gdb.py
rm ./usr/local/lib/libstdc++.dylib
rm ./usr/local/lib/libstdc++.la
rm ./usr/local/lib/libsupc++.a
rm ./usr/local/lib/libsupc++.la
rm ./usr/local/lib/libubsan.0.dylib
rm ./usr/local/lib/libubsan.dylib
rm ./usr/local/lib/libubsan.la
rm ./usr/local/lib/libvt-hyb.0.dylib
rm ./usr/local/lib/libvt-hyb.a
rm ./usr/local/lib/libvt-hyb.dylib
rm ./usr/local/lib/libvt-hyb.la
rm ./usr/local/lib/libvt-mpi-unify.0.dylib
rm ./usr/local/lib/libvt-mpi-unify.a
rm ./usr/local/lib/libvt-mpi-unify.dylib
rm ./usr/local/lib/libvt-mpi-unify.la
rm ./usr/local/lib/libvt-mpi.0.dylib
rm ./usr/local/lib/libvt-mpi.a
rm ./usr/local/lib/libvt-mpi.dylib
rm ./usr/local/lib/libvt-mpi.la
rm ./usr/local/lib/libvt-mt.0.dylib
rm ./usr/local/lib/libvt-mt.a
rm ./usr/local/lib/libvt-mt.dylib
rm ./usr/local/lib/libvt-mt.la
rm ./usr/local/lib/libvt.0.dylib
rm ./usr/local/lib/libvt.a
rm ./usr/local/lib/libvt.dylib
rm ./usr/local/lib/libvt.la
rm ./usr/local/lib/mpi.mod
rm -rf ./usr/local/lib/openmpi
rm ./usr/local/lib/pkgconfig/ompi-c.pc
rm ./usr/local/lib/pkgconfig/ompi-cxx.pc
rm ./usr/local/lib/pkgconfig/ompi-f77.pc
rm ./usr/local/lib/pkgconfig/ompi-f90.pc
rm ./usr/local/lib/pkgconfig/ompi.pc
rm ./usr/local/lib/pkgconfig/orte.pc
rm ./usr/local/lib/x86_64/libiberty.a
rm ./usr/local/libexec
rm ./usr/local/libexec/gcc
rm ./usr/local/libexec/gcc/x86_64-apple-darwin13.0.0
rm -rf ./usr/local/libexec/gcc/x86_64-apple-darwin13.0.0/4.9.0
rm -rf ./usr/local/share/gcc-4.9.0
rm ./usr/local/share/info/cpp.info
rm ./usr/local/share/info/cppinternals.info
rm ./usr/local/share/info/dir
rm ./usr/local/share/info/gcc.info
rm ./usr/local/share/info/gccinstall.info
rm ./usr/local/share/info/gccint.info
rm ./usr/local/share/info/gfortran.info
rm ./usr/local/share/info/libgomp.info
rm ./usr/local/share/info/libitm.info
rm ./usr/local/share/info/libquadmath.info
rm ./usr/local/share/locale/be/LC_MESSAGES
rm ./usr/local/share/locale/be/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/be/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/ca/LC_MESSAGES
rm ./usr/local/share/locale/ca/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/da/LC_MESSAGES
rm ./usr/local/share/locale/da/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/da/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/de/LC_MESSAGES
rm ./usr/local/share/locale/de/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/de/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/el/LC_MESSAGES
rm ./usr/local/share/locale/el/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/el/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/es/LC_MESSAGES
rm ./usr/local/share/locale/es/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/es/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/fi/LC_MESSAGES
rm ./usr/local/share/locale/fi/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/fi/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/fr/LC_MESSAGES
rm ./usr/local/share/locale/fr/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/fr/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/id/LC_MESSAGES
rm ./usr/local/share/locale/id/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/id/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/ja/LC_MESSAGES
rm ./usr/local/share/locale/ja/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/ja/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/nl/LC_MESSAGES
rm ./usr/local/share/locale/nl/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/nl/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/ru/LC_MESSAGES
rm ./usr/local/share/locale/ru/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/ru/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/sr/LC_MESSAGES
rm ./usr/local/share/locale/sr/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/sr/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/sv/LC_MESSAGES
rm ./usr/local/share/locale/sv/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/sv/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/tr/LC_MESSAGES
rm ./usr/local/share/locale/tr/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/tr/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/uk/LC_MESSAGES
rm ./usr/local/share/locale/uk/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/vi/LC_MESSAGES
rm ./usr/local/share/locale/vi/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/vi/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/zh_CN/LC_MESSAGES
rm ./usr/local/share/locale/zh_CN/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/zh_CN/LC_MESSAGES/gcc.mo
rm ./usr/local/share/locale/zh_TW/LC_MESSAGES
rm ./usr/local/share/locale/zh_TW/LC_MESSAGES/cpplib.mo
rm ./usr/local/share/locale/zh_TW/LC_MESSAGES/gcc.mo
rm ./usr/local/share/man/man1/cpp.1
rm ./usr/local/share/man/man1/g++.1
rm ./usr/local/share/man/man1/gcc.1
rm ./usr/local/share/man/man1/gcov.1
rm ./usr/local/share/man/man1/gfortran.1
rm ./usr/local/share/man/man1/mpic++.1
rm ./usr/local/share/man/man1/mpicc.1
rm ./usr/local/share/man/man1/mpicxx.1
rm ./usr/local/share/man/man1/mpiexec.1
rm ./usr/local/share/man/man1/mpif77.1
rm ./usr/local/share/man/man1/mpif90.1
rm ./usr/local/share/man/man1/mpirun.1
rm ./usr/local/share/man/man1/ompi-clean.1
rm ./usr/local/share/man/man1/ompi-iof.1
rm ./usr/local/share/man/man1/ompi-probe.1
rm ./usr/local/share/man/man1/ompi-profiler.1
rm ./usr/local/share/man/man1/ompi-ps.1
rm ./usr/local/share/man/man1/ompi-server.1
rm ./usr/local/share/man/man1/ompi-top.1
rm ./usr/local/share/man/man1/ompi_info.1
rm ./usr/local/share/man/man1/opal_wrapper.1
rm ./usr/local/share/man/man1/orte-clean.1
rm ./usr/local/share/man/man1/orte-iof.1
rm ./usr/local/share/man/man1/orte-ps.1
rm ./usr/local/share/man/man1/orte-top.1
rm ./usr/local/share/man/man1/orted.1
rm ./usr/local/share/man/man1/orterun.1
rm ./usr/local/share/man/man3/MPI.3
rm ./usr/local/share/man/man3/MPI_Abort.3
rm ./usr/local/share/man/man3/MPI_Accumulate.3
rm ./usr/local/share/man/man3/MPI_Add_error_class.3
rm ./usr/local/share/man/man3/MPI_Add_error_code.3
rm ./usr/local/share/man/man3/MPI_Add_error_string.3
rm ./usr/local/share/man/man3/MPI_Address.3
rm ./usr/local/share/man/man3/MPI_Allgather.3
rm ./usr/local/share/man/man3/MPI_Allgatherv.3
rm ./usr/local/share/man/man3/MPI_Alloc_mem.3
rm ./usr/local/share/man/man3/MPI_Allreduce.3
rm ./usr/local/share/man/man3/MPI_Alltoall.3
rm ./usr/local/share/man/man3/MPI_Alltoallv.3
rm ./usr/local/share/man/man3/MPI_Alltoallw.3
rm ./usr/local/share/man/man3/MPI_Attr_delete.3
rm ./usr/local/share/man/man3/MPI_Attr_get.3
rm ./usr/local/share/man/man3/MPI_Attr_put.3
rm ./usr/local/share/man/man3/MPI_Barrier.3
rm ./usr/local/share/man/man3/MPI_Bcast.3
rm ./usr/local/share/man/man3/MPI_Bsend.3
rm ./usr/local/share/man/man3/MPI_Bsend_init.3
rm ./usr/local/share/man/man3/MPI_Buffer_attach.3
rm ./usr/local/share/man/man3/MPI_Buffer_detach.3
rm ./usr/local/share/man/man3/MPI_Cancel.3
rm ./usr/local/share/man/man3/MPI_Cart_coords.3
rm ./usr/local/share/man/man3/MPI_Cart_create.3
rm ./usr/local/share/man/man3/MPI_Cart_get.3
rm ./usr/local/share/man/man3/MPI_Cart_map.3
rm ./usr/local/share/man/man3/MPI_Cart_rank.3
rm ./usr/local/share/man/man3/MPI_Cart_shift.3
rm ./usr/local/share/man/man3/MPI_Cart_sub.3
rm ./usr/local/share/man/man3/MPI_Cartdim_get.3
rm ./usr/local/share/man/man3/MPI_Close_port.3
rm ./usr/local/share/man/man3/MPI_Comm_accept.3
rm ./usr/local/share/man/man3/MPI_Comm_c2f.3
rm ./usr/local/share/man/man3/MPI_Comm_call_errhandler.3
rm ./usr/local/share/man/man3/MPI_Comm_compare.3
rm ./usr/local/share/man/man3/MPI_Comm_connect.3
rm ./usr/local/share/man/man3/MPI_Comm_create.3
rm ./usr/local/share/man/man3/MPI_Comm_create_errhandler.3
rm ./usr/local/share/man/man3/MPI_Comm_create_keyval.3
rm ./usr/local/share/man/man3/MPI_Comm_delete_attr.3
rm ./usr/local/share/man/man3/MPI_Comm_disconnect.3
rm ./usr/local/share/man/man3/MPI_Comm_dup.3
rm ./usr/local/share/man/man3/MPI_Comm_f2c.3
rm ./usr/local/share/man/man3/MPI_Comm_free.3
rm ./usr/local/share/man/man3/MPI_Comm_free_keyval.3
rm ./usr/local/share/man/man3/MPI_Comm_get_attr.3
rm ./usr/local/share/man/man3/MPI_Comm_get_errhandler.3
rm ./usr/local/share/man/man3/MPI_Comm_get_name.3
rm ./usr/local/share/man/man3/MPI_Comm_get_parent.3
rm ./usr/local/share/man/man3/MPI_Comm_group.3
rm ./usr/local/share/man/man3/MPI_Comm_join.3
rm ./usr/local/share/man/man3/MPI_Comm_rank.3
rm ./usr/local/share/man/man3/MPI_Comm_remote_group.3
rm ./usr/local/share/man/man3/MPI_Comm_remote_size.3
rm ./usr/local/share/man/man3/MPI_Comm_set_attr.3
rm ./usr/local/share/man/man3/MPI_Comm_set_errhandler.3
rm ./usr/local/share/man/man3/MPI_Comm_set_name.3
rm ./usr/local/share/man/man3/MPI_Comm_size.3
rm ./usr/local/share/man/man3/MPI_Comm_spawn.3
rm ./usr/local/share/man/man3/MPI_Comm_spawn_multiple.3
rm ./usr/local/share/man/man3/MPI_Comm_split.3
rm ./usr/local/share/man/man3/MPI_Comm_test_inter.3
rm ./usr/local/share/man/man3/MPI_Dims_create.3
rm ./usr/local/share/man/man3/MPI_Errhandler_create.3
rm ./usr/local/share/man/man3/MPI_Errhandler_free.3
rm ./usr/local/share/man/man3/MPI_Errhandler_get.3
rm ./usr/local/share/man/man3/MPI_Errhandler_set.3
rm ./usr/local/share/man/man3/MPI_Error_class.3
rm ./usr/local/share/man/man3/MPI_Error_string.3
rm ./usr/local/share/man/man3/MPI_Exscan.3
rm ./usr/local/share/man/man3/MPI_File_c2f.3
rm ./usr/local/share/man/man3/MPI_File_call_errhandler.3
rm ./usr/local/share/man/man3/MPI_File_close.3
rm ./usr/local/share/man/man3/MPI_File_create_errhandler.3
rm ./usr/local/share/man/man3/MPI_File_delete.3
rm ./usr/local/share/man/man3/MPI_File_f2c.3
rm ./usr/local/share/man/man3/MPI_File_get_amode.3
rm ./usr/local/share/man/man3/MPI_File_get_atomicity.3
rm ./usr/local/share/man/man3/MPI_File_get_byte_offset.3
rm ./usr/local/share/man/man3/MPI_File_get_errhandler.3
rm ./usr/local/share/man/man3/MPI_File_get_group.3
rm ./usr/local/share/man/man3/MPI_File_get_info.3
rm ./usr/local/share/man/man3/MPI_File_get_position.3
rm ./usr/local/share/man/man3/MPI_File_get_position_shared.3
rm ./usr/local/share/man/man3/MPI_File_get_size.3
rm ./usr/local/share/man/man3/MPI_File_get_type_extent.3
rm ./usr/local/share/man/man3/MPI_File_get_view.3
rm ./usr/local/share/man/man3/MPI_File_iread.3
rm ./usr/local/share/man/man3/MPI_File_iread_at.3
rm ./usr/local/share/man/man3/MPI_File_iread_shared.3
rm ./usr/local/share/man/man3/MPI_File_iwrite.3
rm ./usr/local/share/man/man3/MPI_File_iwrite_at.3
rm ./usr/local/share/man/man3/MPI_File_iwrite_shared.3
rm ./usr/local/share/man/man3/MPI_File_open.3
rm ./usr/local/share/man/man3/MPI_File_preallocate.3
rm ./usr/local/share/man/man3/MPI_File_read.3
rm ./usr/local/share/man/man3/MPI_File_read_all.3
rm ./usr/local/share/man/man3/MPI_File_read_all_begin.3
rm ./usr/local/share/man/man3/MPI_File_read_all_end.3
rm ./usr/local/share/man/man3/MPI_File_read_at.3
rm ./usr/local/share/man/man3/MPI_File_read_at_all.3
rm ./usr/local/share/man/man3/MPI_File_read_at_all_begin.3
rm ./usr/local/share/man/man3/MPI_File_read_at_all_end.3
rm ./usr/local/share/man/man3/MPI_File_read_ordered.3
rm ./usr/local/share/man/man3/MPI_File_read_ordered_begin.3
rm ./usr/local/share/man/man3/MPI_File_read_ordered_end.3
rm ./usr/local/share/man/man3/MPI_File_read_shared.3
rm ./usr/local/share/man/man3/MPI_File_seek.3
rm ./usr/local/share/man/man3/MPI_File_seek_shared.3
rm ./usr/local/share/man/man3/MPI_File_set_atomicity.3
rm ./usr/local/share/man/man3/MPI_File_set_errhandler.3
rm ./usr/local/share/man/man3/MPI_File_set_info.3
rm ./usr/local/share/man/man3/MPI_File_set_size.3
rm ./usr/local/share/man/man3/MPI_File_set_view.3
rm ./usr/local/share/man/man3/MPI_File_sync.3
rm ./usr/local/share/man/man3/MPI_File_write.3
rm ./usr/local/share/man/man3/MPI_File_write_all.3
rm ./usr/local/share/man/man3/MPI_File_write_all_begin.3
rm ./usr/local/share/man/man3/MPI_File_write_all_end.3
rm ./usr/local/share/man/man3/MPI_File_write_at.3
rm ./usr/local/share/man/man3/MPI_File_write_at_all.3
rm ./usr/local/share/man/man3/MPI_File_write_at_all_begin.3
rm ./usr/local/share/man/man3/MPI_File_write_at_all_end.3
rm ./usr/local/share/man/man3/MPI_File_write_ordered.3
rm ./usr/local/share/man/man3/MPI_File_write_ordered_begin.3
rm ./usr/local/share/man/man3/MPI_File_write_ordered_end.3
rm ./usr/local/share/man/man3/MPI_File_write_shared.3
rm ./usr/local/share/man/man3/MPI_Finalize.3
rm ./usr/local/share/man/man3/MPI_Finalized.3
rm ./usr/local/share/man/man3/MPI_Free_mem.3
rm ./usr/local/share/man/man3/MPI_Gather.3
rm ./usr/local/share/man/man3/MPI_Gatherv.3
rm ./usr/local/share/man/man3/MPI_Get.3
rm ./usr/local/share/man/man3/MPI_Get_address.3
rm ./usr/local/share/man/man3/MPI_Get_count.3
rm ./usr/local/share/man/man3/MPI_Get_elements.3
rm ./usr/local/share/man/man3/MPI_Get_processor_name.3
rm ./usr/local/share/man/man3/MPI_Get_version.3
rm ./usr/local/share/man/man3/MPI_Graph_create.3
rm ./usr/local/share/man/man3/MPI_Graph_get.3
rm ./usr/local/share/man/man3/MPI_Graph_map.3
rm ./usr/local/share/man/man3/MPI_Graph_neighbors.3
rm ./usr/local/share/man/man3/MPI_Graph_neighbors_count.3
rm ./usr/local/share/man/man3/MPI_Graphdims_get.3
rm ./usr/local/share/man/man3/MPI_Grequest_complete.3
rm ./usr/local/share/man/man3/MPI_Grequest_start.3
rm ./usr/local/share/man/man3/MPI_Group_c2f.3
rm ./usr/local/share/man/man3/MPI_Group_compare.3
rm ./usr/local/share/man/man3/MPI_Group_difference.3
rm ./usr/local/share/man/man3/MPI_Group_excl.3
rm ./usr/local/share/man/man3/MPI_Group_f2c.3
rm ./usr/local/share/man/man3/MPI_Group_free.3
rm ./usr/local/share/man/man3/MPI_Group_incl.3
rm ./usr/local/share/man/man3/MPI_Group_intersection.3
rm ./usr/local/share/man/man3/MPI_Group_range_excl.3
rm ./usr/local/share/man/man3/MPI_Group_range_incl.3
rm ./usr/local/share/man/man3/MPI_Group_rank.3
rm ./usr/local/share/man/man3/MPI_Group_size.3
rm ./usr/local/share/man/man3/MPI_Group_translate_ranks.3
rm ./usr/local/share/man/man3/MPI_Group_union.3
rm ./usr/local/share/man/man3/MPI_Ibsend.3
rm ./usr/local/share/man/man3/MPI_Info_c2f.3
rm ./usr/local/share/man/man3/MPI_Info_create.3
rm ./usr/local/share/man/man3/MPI_Info_delete.3
rm ./usr/local/share/man/man3/MPI_Info_dup.3
rm ./usr/local/share/man/man3/MPI_Info_f2c.3
rm ./usr/local/share/man/man3/MPI_Info_free.3
rm ./usr/local/share/man/man3/MPI_Info_get.3
rm ./usr/local/share/man/man3/MPI_Info_get_nkeys.3
rm ./usr/local/share/man/man3/MPI_Info_get_nthkey.3
rm ./usr/local/share/man/man3/MPI_Info_get_valuelen.3
rm ./usr/local/share/man/man3/MPI_Info_set.3
rm ./usr/local/share/man/man3/MPI_Init.3
rm ./usr/local/share/man/man3/MPI_Init_thread.3
rm ./usr/local/share/man/man3/MPI_Initialized.3
rm ./usr/local/share/man/man3/MPI_Intercomm_create.3
rm ./usr/local/share/man/man3/MPI_Intercomm_merge.3
rm ./usr/local/share/man/man3/MPI_Iprobe.3
rm ./usr/local/share/man/man3/MPI_Irecv.3
rm ./usr/local/share/man/man3/MPI_Irsend.3
rm ./usr/local/share/man/man3/MPI_Is_thread_main.3
rm ./usr/local/share/man/man3/MPI_Isend.3
rm ./usr/local/share/man/man3/MPI_Issend.3
rm ./usr/local/share/man/man3/MPI_Keyval_create.3
rm ./usr/local/share/man/man3/MPI_Keyval_free.3
rm ./usr/local/share/man/man3/MPI_Lookup_name.3
rm ./usr/local/share/man/man3/MPI_Op_c2f.3
rm ./usr/local/share/man/man3/MPI_Op_create.3
rm ./usr/local/share/man/man3/MPI_Op_f2c.3
rm ./usr/local/share/man/man3/MPI_Op_free.3
rm ./usr/local/share/man/man3/MPI_Open_port.3
rm ./usr/local/share/man/man3/MPI_Pack.3
rm ./usr/local/share/man/man3/MPI_Pack_external.3
rm ./usr/local/share/man/man3/MPI_Pack_external_size.3
rm ./usr/local/share/man/man3/MPI_Pack_size.3
rm ./usr/local/share/man/man3/MPI_Pcontrol.3
rm ./usr/local/share/man/man3/MPI_Probe.3
rm ./usr/local/share/man/man3/MPI_Publish_name.3
rm ./usr/local/share/man/man3/MPI_Put.3
rm ./usr/local/share/man/man3/MPI_Query_thread.3
rm ./usr/local/share/man/man3/MPI_Recv.3
rm ./usr/local/share/man/man3/MPI_Recv_init.3
rm ./usr/local/share/man/man3/MPI_Reduce.3
rm ./usr/local/share/man/man3/MPI_Reduce_local.3
rm ./usr/local/share/man/man3/MPI_Reduce_scatter.3
rm ./usr/local/share/man/man3/MPI_Register_datarep.3
rm ./usr/local/share/man/man3/MPI_Request_c2f.3
rm ./usr/local/share/man/man3/MPI_Request_f2c.3
rm ./usr/local/share/man/man3/MPI_Request_free.3
rm ./usr/local/share/man/man3/MPI_Request_get_status.3
rm ./usr/local/share/man/man3/MPI_Rsend.3
rm ./usr/local/share/man/man3/MPI_Rsend_init.3
rm ./usr/local/share/man/man3/MPI_Scan.3
rm ./usr/local/share/man/man3/MPI_Scatter.3
rm ./usr/local/share/man/man3/MPI_Scatterv.3
rm ./usr/local/share/man/man3/MPI_Send.3
rm ./usr/local/share/man/man3/MPI_Send_init.3
rm ./usr/local/share/man/man3/MPI_Sendrecv.3
rm ./usr/local/share/man/man3/MPI_Sendrecv_replace.3
rm ./usr/local/share/man/man3/MPI_Sizeof.3
rm ./usr/local/share/man/man3/MPI_Ssend.3
rm ./usr/local/share/man/man3/MPI_Ssend_init.3
rm ./usr/local/share/man/man3/MPI_Start.3
rm ./usr/local/share/man/man3/MPI_Startall.3
rm ./usr/local/share/man/man3/MPI_Status_c2f.3
rm ./usr/local/share/man/man3/MPI_Status_f2c.3
rm ./usr/local/share/man/man3/MPI_Status_set_cancelled.3
rm ./usr/local/share/man/man3/MPI_Status_set_elements.3
rm ./usr/local/share/man/man3/MPI_Test.3
rm ./usr/local/share/man/man3/MPI_Test_cancelled.3
rm ./usr/local/share/man/man3/MPI_Testall.3
rm ./usr/local/share/man/man3/MPI_Testany.3
rm ./usr/local/share/man/man3/MPI_Testsome.3
rm ./usr/local/share/man/man3/MPI_Topo_test.3
rm ./usr/local/share/man/man3/MPI_Type_c2f.3
rm ./usr/local/share/man/man3/MPI_Type_commit.3
rm ./usr/local/share/man/man3/MPI_Type_contiguous.3
rm ./usr/local/share/man/man3/MPI_Type_create_darray.3
rm ./usr/local/share/man/man3/MPI_Type_create_f90_complex.3
rm ./usr/local/share/man/man3/MPI_Type_create_f90_integer.3
rm ./usr/local/share/man/man3/MPI_Type_create_f90_real.3
rm ./usr/local/share/man/man3/MPI_Type_create_hindexed.3
rm ./usr/local/share/man/man3/MPI_Type_create_hvector.3
rm ./usr/local/share/man/man3/MPI_Type_create_indexed_block.3
rm ./usr/local/share/man/man3/MPI_Type_create_keyval.3
rm ./usr/local/share/man/man3/MPI_Type_create_resized.3
rm ./usr/local/share/man/man3/MPI_Type_create_struct.3
rm ./usr/local/share/man/man3/MPI_Type_create_subarray.3
rm ./usr/local/share/man/man3/MPI_Type_delete_attr.3
rm ./usr/local/share/man/man3/MPI_Type_dup.3
rm ./usr/local/share/man/man3/MPI_Type_extent.3
rm ./usr/local/share/man/man3/MPI_Type_f2c.3
rm ./usr/local/share/man/man3/MPI_Type_free.3
rm ./usr/local/share/man/man3/MPI_Type_free_keyval.3
rm ./usr/local/share/man/man3/MPI_Type_get_attr.3
rm ./usr/local/share/man/man3/MPI_Type_get_contents.3
rm ./usr/local/share/man/man3/MPI_Type_get_envelope.3
rm ./usr/local/share/man/man3/MPI_Type_get_extent.3
rm ./usr/local/share/man/man3/MPI_Type_get_name.3
rm ./usr/local/share/man/man3/MPI_Type_get_true_extent.3
rm ./usr/local/share/man/man3/MPI_Type_hindexed.3
rm ./usr/local/share/man/man3/MPI_Type_hvector.3
rm ./usr/local/share/man/man3/MPI_Type_indexed.3
rm ./usr/local/share/man/man3/MPI_Type_lb.3
rm ./usr/local/share/man/man3/MPI_Type_match_size.3
rm ./usr/local/share/man/man3/MPI_Type_set_attr.3
rm ./usr/local/share/man/man3/MPI_Type_set_name.3
rm ./usr/local/share/man/man3/MPI_Type_size.3
rm ./usr/local/share/man/man3/MPI_Type_struct.3
rm ./usr/local/share/man/man3/MPI_Type_ub.3
rm ./usr/local/share/man/man3/MPI_Type_vector.3
rm ./usr/local/share/man/man3/MPI_Unpack.3
rm ./usr/local/share/man/man3/MPI_Unpack_external.3
rm ./usr/local/share/man/man3/MPI_Unpublish_name.3
rm ./usr/local/share/man/man3/MPI_Wait.3
rm ./usr/local/share/man/man3/MPI_Waitall.3
rm ./usr/local/share/man/man3/MPI_Waitany.3
rm ./usr/local/share/man/man3/MPI_Waitsome.3
rm ./usr/local/share/man/man3/MPI_Win_c2f.3
rm ./usr/local/share/man/man3/MPI_Win_call_errhandler.3
rm ./usr/local/share/man/man3/MPI_Win_complete.3
rm ./usr/local/share/man/man3/MPI_Win_create.3
rm ./usr/local/share/man/man3/MPI_Win_create_errhandler.3
rm ./usr/local/share/man/man3/MPI_Win_create_keyval.3
rm ./usr/local/share/man/man3/MPI_Win_delete_attr.3
rm ./usr/local/share/man/man3/MPI_Win_f2c.3
rm ./usr/local/share/man/man3/MPI_Win_fence.3
rm ./usr/local/share/man/man3/MPI_Win_free.3
rm ./usr/local/share/man/man3/MPI_Win_free_keyval.3
rm ./usr/local/share/man/man3/MPI_Win_get_attr.3
rm ./usr/local/share/man/man3/MPI_Win_get_errhandler.3
rm ./usr/local/share/man/man3/MPI_Win_get_group.3
rm ./usr/local/share/man/man3/MPI_Win_get_name.3
rm ./usr/local/share/man/man3/MPI_Win_lock.3
rm ./usr/local/share/man/man3/MPI_Win_post.3
rm ./usr/local/share/man/man3/MPI_Win_set_attr.3
rm ./usr/local/share/man/man3/MPI_Win_set_errhandler.3
rm ./usr/local/share/man/man3/MPI_Win_set_name.3
rm ./usr/local/share/man/man3/MPI_Win_start.3
rm ./usr/local/share/man/man3/MPI_Win_test.3
rm ./usr/local/share/man/man3/MPI_Win_unlock.3
rm ./usr/local/share/man/man3/MPI_Win_wait.3
rm ./usr/local/share/man/man3/MPI_Wtick.3
rm ./usr/local/share/man/man3/MPI_Wtime.3
rm ./usr/local/share/man/man3/OpenMPI.3
rm ./usr/local/share/man/man7/fsf-funding.7
rm ./usr/local/share/man/man7/gfdl.7
rm ./usr/local/share/man/man7/gpl.7
rm ./usr/local/share/man/man7/ompi_crcp.7
rm ./usr/local/share/man/man7/opal_crs.7
rm ./usr/local/share/man/man7/orte_filem.7
rm ./usr/local/share/man/man7/orte_hosts.7
rm ./usr/local/share/man/man7/orte_snapc.7
rm -rf ./usr/local/share/openmpi
rm -rf  ./usr/local/share/vampirtrace
exit 0