SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -DBAMG_LONG_LONG")

IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHAVE_UNISTD_H" )
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")

IF(CMAKE_BUILD_TYPE EQUAL "Debug")
    SET(CMAKE_CXX_FLAGS "${FF_CXX_FLAGS} -DCHECK_KN -g" )
    IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
        SET(CMAKE_CXX_FLAGS "${FF_CXX_FLAGS} -fno-inline -fexceptions" )
    ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
ELSE()
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DNCHECKPTR -O3" )
ENDIF(CMAKE_BUILD_TYPE EQUAL "Debug")

