INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(CCOLAMD_INCLUDES NAMES ccolamd.h 
                          PATHS ${PACKMAN_INCLUDE_PATHS} 
                          PATH_SUFFIXES suitesparse)

FIND_LIBRARY(CCOLAMD_LIBRARIES NAMES ccolamd 
                           PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(CCOLAMD_INCLUDES AND CCOLAMD_LIBRARIES)
  SET(CCOLAMD_FOUND True)
ENDIF(CCOLAMD_INCLUDES AND CCOLAMD_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CCOLAMD DEFAULT_MSG CCOLAMD_INCLUDES CCOLAMD_LIBRARIES)


