INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_LIBRARY(ARPACK_LIBRARIES NAMES arpack 
                             PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(ARPACK_LIBRARIES)
  SET(ARPACK_FOUND True)
ENDIF(ARPACK_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(ARPACK DEFAULT_MSG ARPACK_LIBRARIES)

