INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(NLOPT_INCLUDES NAMES nlopt.hpp 
                         PATHS ${PACKMAN_INCLUDE_PATHS})

FIND_LIBRARY(NLOPT_LIBRARIES NAMES nlopt 
                             PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(NLOPT_LIBRARIES)
  SET(NLOPT_FOUND True)
  MESSAGE(STATUS "A library with NLOPT API found.")
ENDIF(NLOPT_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(NLOPT DEFAULT_MSG NLOPT_INCLUDES NLOPT_LIBRARIES)




