INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(FFTW_INCLUDES NAMES fftw3.h 
                        PATHS ${PACKMAN_INCLUDE_PATHS}) 

FIND_LIBRARY(FFTW_LIBRARIES NAMES fftw3 
                            PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(FFTW_INCLUDES AND FFTW_LIBRARIES)
  SET(FFTW_FOUND True)
  MESSAGE(STATUS "A library with FFTW API found.")
ENDIF(FFTW_INCLUDES AND FFTW_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(FFTW DEFAULT_MSG FFTW_INCLUDES FFTW_LIBRARIES)



