INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(COLAMD_INCLUDES NAMES colamd.h 
                          PATHS ${PACKMAN_INCLUDE_PATHS} 
                          PATH_SUFFIXES suitesparse)

FIND_LIBRARY(COLAMD_LIBRARIES NAMES colamd 
                           PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(COLAMD_INCLUDES AND COLAMD_LIBRARIES)
  SET(COLAMD_FOUND True)
ENDIF(COLAMD_INCLUDES AND COLAMD_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(COLAMD DEFAULT_MSG COLAMD_INCLUDES COLAMD_LIBRARIES)


