INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(AMD_INCLUDES NAMES amd.h 
                          PATHS ${PACKMAN_INCLUDE_PATHS} 
                          PATH_SUFFIXES suitesparse)

FIND_LIBRARY(AMD_LIBRARIES NAMES amd 
                           PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(AMD_INCLUDES AND AMD_LIBRARIES)
  SET(AMD_FOUND True)
ENDIF(AMD_INCLUDES AND AMD_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(AMD DEFAULT_MSG AMD_INCLUDES AMD_LIBRARIES)


