INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(CAMD_INCLUDES NAMES camd.h 
                          PATHS ${PACKMAN_INCLUDE_PATHS} 
                          PATH_SUFFIXES suitesparse)

FIND_LIBRARY(CAMD_LIBRARIES NAMES camd 
                           PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(CAMD_INCLUDES AND CAMD_LIBRARIES)
  SET(CAMD_FOUND True)
ENDIF(CAMD_INCLUDES AND CAMD_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CAMD DEFAULT_MSG CAMD_INCLUDES CAMD_LIBRARIES)


