INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(PARMETIS_INCLUDES NAMES parmetis.h 
                            PATHS ${PACKMAN_INCLUDE_PATHS}) 

FIND_LIBRARY(PARMETIS_LIBRARIES NAMES parmetis 
                                PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(PARMETIS_INCLUDES AND PARMETIS_LIBRARIES)
  SET(PARMETIS_FOUND True)
ENDIF(PARMETIS_INCLUDES AND PARMETIS_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(PARMETIS DEFAULT_MSG PARMETIS_INCLUDES PARMETIS_LIBRARIES)





