INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_LIBRARY(SUITESPARSECONFIG_LIBRARIES NAMES suitesparseconfig 
                           PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(SUITESPARSECONFIG_LIBRARIES)
  SET(SUITESPARSECONFIG_FOUND True)
ENDIF(SUITESPARSECONFIG_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SUITESPARSECONFIG DEFAULT_MSG SUITESPARSECONFIG_LIBRARIES)


