INCLUDE(FindPackageHandleStandardArgs)

SET(SCOTCH_FOUND False)

IF(SCOTCH_INCLUDES AND SCOTCH_LIBRARIES)

  SET(SCOTCH_FOUND True)

ELSE(SCOTCH_INCLUDES AND SCOTCH_LIBRARIES)

  FIND_PATH(SCOTCH_INCLUDES NAMES scotch.h PATHS /usr/include PATH_SUFFIXES scotch)
  FIND_LIBRARY(SCOTCH_LIBRARIES NAMES scotch PATHS /usr/lib)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(SCOTCH DEFAULT_MSG SCOTCH_INCLUDES SCOTCH_LIBRARIES)

ENDIF(SCOTCH_INCLUDES AND SCOTCH_LIBRARIES)

