INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(PackageManagerPaths)

FIND_PATH(METIS_INCLUDES NAMES metis.h 
                        PATHS ${PACKMAN_INCLUDE_PATHS}) 

FIND_LIBRARY(METIS_LIBRARIES NAMES metis 
                            PATHS ${PACKMAN_LIBRARIES_PATHS})

IF(METIS_INCLUDES AND METIS_LIBRARIES)
  SET(METIS_FOUND True)
  MESSAGE(STATUS "A library with METIS API found.")
ENDIF(METIS_INCLUDES AND METIS_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(METIS DEFAULT_MSG METIS_INCLUDES METIS_LIBRARIES)




