FUNCTION(FREEFEM_FIND_PACKAGE PACKAGE)

  FIND_PACKAGE(${PACKAGE})

  IF(${PACKAGE}_FOUND)

    # Unifying variables names for include directory paths

    SET(POSSIBLE_INCLUDE_PATH_VARIABLES "${PACKAGE}_INCLUDE"
                                        "${PACKAGE}_INCLUDES"
                                        "${PACKAGE}_INCLUDE_PATH"
                                        "${PACKAGE}_INCLUDE_PATHS"
                                        "${PACKAGE}_C_INCLUDE_PATHS")

    FOREACH(INCLUDE_PATH_VARIABLE IN LISTS ${POSSIBLE_INCLUDE_PATH_VARIABLES}) 
      LIST(APPEND INCLUDE_PATHS ${INCLUDE_PATH_VARIABLE})
    ENDFOREACH(INCLUDE_PATH_VARIABLE)

    # Unifying variables names for library directory paths

    SET(POSSIBLE_LIBRARIES_VARIABLES "${PACKAGE}_LIBRARY"
                                     "${PACKAGE}_LIBRARIES"
                                     "${PACKAGE}_C_LIBRARY"
                                     "${PACKAGE}_C_LIBRARIES")

    FOREACH(LIBRARIES_VARIABLE IN LISTS ${POSSIBLE_LIBRARIES_VARIABLES}) 
      LIST(APPEND LIBRARIES ${LIBRARIES_VARIABLE})
    ENDFOREACH(LIBRARIES_VARIABLE)

    IF(FREEFEM_VERBOSE)
      MESSAGE(STATUS "FREEFEM_FIND_PACKAGE(${PACKAGE}: INCLUDE_PATHS = ${INCLUDE_PATHS}")
      MESSAGE(STATUS "FREEFEM_FIND_PACKAGE(${PACKAGE}: LIBRARIES = ${LIBRARIES}")
    ENDIF(FREEFEM_VERBOSE)

    # Return unified names

    SET(FREEFEM_${PACKAGE}_INSTALLED TRUE PARENT_SCOPE)
    SET(FREEFEM_${PACKAGE}_INCLUDE_PATHS ${INCLUDE_PATHS} PARENT_SCOPE)
    SET(FREEFEM_${PACKAGE}_LIBRARIES ${LIBRARIES} PARENT_SCOPE)
  
    ADD_LIBRARY(FREEFEM::${PACKAGE} UNKNOWN IMPORTED)
    SET_TARGET_PROPERTIES(FREEFEM::${PACKAGE} PROPERTIES IMPORTED_LOCATION ${LIBRARIES})
    SET_TARGET_PROPERTIES(FREEFEM::${PACKAGE} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${INCLUDE_PATHS}")
  
  ENDIF(${PACKAGE}_FOUND)

ENDFUNCTION(FREEFEM_FIND_PACKAGE)
