FIND_PACKAGE(CBLAS)
FIND_PACKAGE(HDF5)

FIND_PACKAGE(ARPACK)
FIND_PACKAGE(UMFPACK)
FIND_PACKAGE(GLUT)
FIND_PACKAGE(GSL)
FIND_PACKAGE(LAPACK)
FIND_PACKAGE(MPI)
FIND_PACKAGE(OpenGL)
FIND_PACKAGE(Threads)

#  INCLUDE(FFInstallPackage)
#FF_INSTALL_PACKAGE(PETSC)


LIST(APPEND MODULE_LIST FFTW
                        GMM
                        IPOPT
                        METIS
                        MUMPS
                        NLOPT
                        SCOTCH
                        SUPERLU
                        TETGEN)


FOREACH(MODULE ${MODULE_LIST})
  FIND_PACKAGE(${MODULE})
  IF(NOT ${MODULE}_FOUND)
    LIST(APPEND DOWNLOAD_LIST ${MODULE})
  ENDIF(NOT ${MODULE}_FOUND)

ENDFOREACH(MODULE)

IF(ENABLE_DOWNLOAD)
  MESSAGE(STATUS "The following modules will be downloaded: ${DOWNLOAD_LIST}")
  INCLUDE(FFInstallPackage)
  FOREACH(MODULE ${DOWNLOAD_LIST})
    FF_INSTALL_PACKAGE(${MODULE}) 
  ENDFOREACH(MODULE)
ELSE()
  MESSAGE(STATUS "The following modules are missing: ${DOWNLOAD_LIST}")
ENDIF(ENABLE_DOWNLOAD)



