FIND_PACKAGE(HDF5 REQUIRED)
FIND_PACKAGE(GLUT REQUIRED)
FIND_PACKAGE(OpenGL REQUIRED)
FIND_PACKAGE(Threads REQUIRED)
FIND_PACKAGE(MPI REQUIRED)


FIND_PACKAGE(GSL)
FIND_PACKAGE(LAPACK)
FIND_PACKAGE(SCOTCH)


