# Full version of FreeFem, using MPICH installed by PETSc
name: Full version MPICH

on:
  push:
    branches:
      - develop
      - master

  pull_request:
    branches:
      - develop

  # For development phase
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        version: [22.04, 24.04]
        cfg:
        - {opts: --enable-debug}
        - {opts: --enable-optim --enable-generic}

    name: Ubuntu ${{ matrix.version }} with ${{ matrix.cfg.opts }} \
            - ${{ github.workflow }}

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt update
          sudo apt install gcc g++ gfortran m4 patch git wget cmake \
          libhdf5-dev flex bison autoconf automake \
          autotools-dev

      - name: Extract PETSc and runner info
        id: petsc-info
        run: |
          VERSION=$(grep -E -o "petsc-([0-9]{1,}\.)+[0-9]{1,}" 3rdparty/getall | head -1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image=$ImageOS" >> $GITHUB_OUTPUT
          echo "home=$HOME" >> $GITHUB_OUTPUT

      - name: Cache PETSc installation
        id: cache-petsc
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.petsc-info.outputs.home }}/freefem/ff-petsc
          key: petsc-${{ github.workflow }}-${{ steps.petsc-info.outputs.image }}-${{ matrix.cfg.opts }}-${{ steps.petsc-info.outputs.version }}-${{ hashFiles('3rdparty/ff-petsc/Makefile') }}
          
      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download ${{ matrix.cfg.opts }} \
          --prefix="${HOME}/freefem"

      - name: PETSc
        if: steps.cache-petsc.outputs.cache-hit != 'true'
        run: |
          ./3rdparty/getall -a -o PETSc
          cd 3rdparty/ff-petsc
          make petsc-slepc
          cd -
          ./reconfigure

      - name: Upload PETSc and reconfigure logs on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: PETSc-reconfigure-logs
          path: |
            3rdparty/ff-petsc/petsc-*/configure.log
            config.log
          compression-level: 9

      - name: Build
        run: make -j 4

      - name: Check
        run: |
          make check -i
          ./etc/actions/failed_tests_logs.sh

      - name: Install
        run: make install

  macos:
    strategy:
      fail-fast: false
      matrix:
        version: [14, 15, 26]
        cfg:
        - {opts: --enable-debug}
        - {opts: --enable-optim --enable-generic}

    name: macOS ${{ matrix.version }} with ${{ matrix.cfg.opts }} \
      - ${{ github.workflow }}

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      # Remove homebrew LLVM compiler, and use most recent Xcode development
      # tools
      - name: Set environment
        run: |
          if (( ${{ matrix.version }} == 15 )); then
            echo "LLVM_VERSION=18" >> $GITHUB_ENV
            sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          elif (( ${{ matrix.version }} == 14 )); then
            echo "LLVM_VERSION=15" >> $GITHUB_ENV
            sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          fi

      - name: Install
        run: |
          brew install m4 bison autoconf automake
          if (( ${{ matrix.version }} != 26 )); then
            brew remove llvm@$LLVM_VERSION
          fi

      - name: Symlink gfortran
        run: ./etc/actions/macos/link_fortran.sh "$(uname -p)"

      - name: Extract PETSc and runner info
        id: petsc-info
        run: |
          VERSION=$(grep -E -o "petsc-([0-9]{1,}\.)+[0-9]{1,}" 3rdparty/getall | head -1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image=$ImageOS" >> $GITHUB_OUTPUT
          echo "home=$HOME" >> $GITHUB_OUTPUT

      - name: Cache PETSc installation
        id: cache-petsc
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.petsc-info.outputs.home }}/freefem/ff-petsc
          key: petsc-${{ github.workflow }}-${{ steps.petsc-info.outputs.image }}-${{ matrix.cfg.opts }}-${{ steps.petsc-info.outputs.version }}-${{ hashFiles('3rdparty/ff-petsc/Makefile') }}
          
      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download ${{ matrix.cfg.opts }} \
          --prefix="${HOME}/freefem"

      - name: PETSc
        if: steps.cache-petsc.outputs.cache-hit != 'true'
        run: |
          ./3rdparty/getall -a -o PETSc
          cd 3rdparty/ff-petsc
          make petsc-slepc
          cd -
          ./reconfigure

      - name: Upload PETSc and reconfigure logs on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: PETSc-reconfigure-logs
          path: |
            3rdparty/ff-petsc/petsc-*/configure.log
            config.log
          compression-level: 9

      - name: Build
        run: make -j 3

      - name: Check
        run: |
          make check -i
          ./etc/actions/failed_tests_logs.sh

      - name: Install
        run: make install
