name: Job3
on: [push]

jobs:
  linux:
    strategy:
      matrix:
        version: [20.04, 22.04]

    continue-on-error: true
    name: Job1 - Ubuntu ${{ matrix.version }}
    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: |
          sudo apt update
          sudo apt install gcc g++ gfortran m4 patch \
            git libblas-dev liblapack-dev libsuitesparse-dev \
            libhdf5-dev libgsl-dev flex bison wget cmake autoconf \
            automake autotools-dev

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --without-mpi --prefix="${HOME}/freefem"
          ./3rdparty/getall -a -o ARPACK,METIS,ParMETIS,ScaLAPACK,Scotch,SuiteSparse,SuperLU,mmg,parmmg,hpddm,bemtool,Boost,libpthread-google,TetGen,Ipopt,NLopt,freeYams,FFTW,Gmm++,MMG3D,mshmet,MUMPS,htool

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: make install

  macos:
    strategy:
      matrix:
        version: [11, 12]

    continue-on-error: true
    name: Job1 - MacOS ${{ matrix.version }}
    runs-on: macos-${{ matrix.version }}

    env:
      CC: clang
      CXX: clang++
      FC: gfortran
      F77: gfortran

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: brew install gcc m4 git flex bison suitesparse hdf5 cmake wget autoconf automake

      - name: Symlink GCC & Fortran
        run: |
          sudo ln -fs /usr/local/bin/gfortran-12 /usr/local/bin/gfortran   
          sudo ln -fs /usr/local/bin/gcc-12 /usr/local/bin/gcc
          sudo ln -fs /usr/local/bin/g++-12 /usr/local/bin/g++

          # symlink dylib location for previous versions
          sudo ln -fs /usr/local/opt/gcc/lib/gcc/12 /usr/local/opt/gcc/lib/gcc/11
          sudo ln -fs /usr/local/opt/gcc/lib/gcc/12 /usr/local/opt/gcc/lib/gcc/10

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --without-mpi --prefix="${HOME}/freefem"
          ./3rdparty/getall -a -o ARPACK,METIS,ParMETIS,ScaLAPACK,Scotch,SuiteSparse,SuperLU,mmg,parmmg,hpddm,bemtool,Boost,libpthread-google,TetGen,Ipopt,NLopt,freeYams,FFTW,Gmm++,MMG3D,mshmet,MUMPS,htool

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: make install

  windows:
    name: Job3 - Windows
    runs-on: windows-latest

    steps:
      - name: TODO
        run: echo TODO
