name: Job3 - Sequential FreeFEM version
on: [push]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        version: [20.04, 22.04]

    name: Job3 - Ubuntu ${{ matrix.version }}
    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: |
          sudo apt update
          sudo apt install gcc g++ gfortran m4 patch \
            git libblas-dev liblapack-dev libsuitesparse-dev \
            libhdf5-dev libgsl-dev flex bison wget cmake autoconf \
            automake autotools-dev

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --without-mpi --prefix="${HOME}/freefem"
          ./3rdparty/getall -a -o ARPACK,METIS,ParMETIS,ScaLAPACK,Scotch,SuiteSparse,SuperLU,mmg,parmmg,hpddm,bemtool,Boost,libpthread-google,TetGen,Ipopt,NLopt,freeYams,FFTW,Gmm++,MMG3D,mshmet,MUMPS,htool

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: make install

  macos:
    strategy:
      fail-fast: false
      matrix:
        version: [11, 12]

    name: Job3 - MacOS ${{ matrix.version }}
    runs-on: macos-${{ matrix.version }}

    env:
      CC: clang
      CXX: clang++
      FC: gfortran
      F77: gfortran

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: brew install gcc m4 git flex bison suitesparse hdf5 cmake wget autoconf automake

      - name: Symlink GCC & Fortran
        run: ./etc/actions/macos/link_fortran.sh

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --without-mpi --prefix="${HOME}/freefem"
          ./3rdparty/getall -a -o ARPACK,METIS,ParMETIS,ScaLAPACK,Scotch,SuiteSparse,SuperLU,mmg,parmmg,hpddm,bemtool,Boost,libpthread-google,TetGen,Ipopt,NLopt,freeYams,FFTW,Gmm++,MMG3D,mshmet,MUMPS,htool

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: sudo make install #TODO should work without sudo

  windows:
    name: Job3 - Windows
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            make
            m4
            patch
            git
            flex
            bison
            unzip
            mingw-w64-x86_64-openblas
            mingw-w64-x86_64-hdf5
            mingw-w64-x86_64-gsl
            autoconf
            automake-wrapper
            pkg-config
            pkgfile
            tar
            mingw-w64-x86_64-cmake

      - uses: actions/checkout@v4

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --without-mpi --prefix="${HOME}/freefem"
          ./3rdparty/getall -a -o ARPACK,METIS,ParMETIS,ScaLAPACK,Scotch,SuiteSparse,SuperLU,mmg,parmmg,hpddm,bemtool,Boost,libpthread-google,TetGen,Ipopt,NLopt,freeYams,FFTW,Gmm++,MMG3D,mshmet,MUMPS,htool

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: make install
