name: Job4 OpenMPI - Full FreeFEM version [release mode]
on: [push]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        version: [20.04, 22.04]

    name: Job4 OpenMPI - Ubuntu ${{ matrix.version }}
    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: |
          sudo apt update
          sudo apt install gcc g++ gfortran m4 patch \
            git libblas-dev liblapack-dev libsuitesparse-dev \
            libhdf5-dev libgsl-dev flex bison wget cmake autoconf \
            automake autotools-dev \
            libopenmpi-dev

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --prefix="${HOME}/freefem"
          ./3rdparty/getall -a -o PETSc

      - name: PETSc
        run: |
          cd 3rdparty/ff-petsc
          make petsc-slepc
          cd -
          ./reconfigure

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: make install

  macos:
    strategy:
      fail-fast: false
      matrix:
        version: [11, 12]

    name: Job4 OpenMPI - MacOS ${{ matrix.version }}
    runs-on: macos-${{ matrix.version }}

    env:
      CC: gcc
      CXX: g++
      FC: gfortran
      F77: gfortran

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: brew install gcc m4 git flex bison suitesparse hdf5 cmake wget autoconf automake open-mpi

      - name: Symlink GCC & Fortran
        run: |
          sudo ln -fs /usr/local/bin/gfortran-12 /usr/local/bin/gfortran   
          sudo ln -fs /usr/local/bin/gcc-12 /usr/local/bin/gcc
          sudo ln -fs /usr/local/bin/g++-12 /usr/local/bin/g++

          # symlink dylib location for previous versions
          sudo ln -fs /usr/local/opt/gcc/lib/gcc/12 /usr/local/opt/gcc/lib/gcc/11
          sudo ln -fs /usr/local/opt/gcc/lib/gcc/12 /usr/local/opt/gcc/lib/gcc/10

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --prefix="${HOME}/freefem"
          ./3rdparty/getall -a -o PETSc

      - name: PETSc
        run: |
          cd 3rdparty/ff-petsc
          make petsc-slepc
          cd -
          ./reconfigure

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: make install
