name: Job5 MSMPI - Full FreeFEM version [debug mode]
on: [push]

jobs:
  windows:
    name: Job5 MSMPI - Windows
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: msmpi

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: strict
          install: >-
            mingw-w64-x86_64-toolchain
            make
            m4
            patch
            git
            flex
            bison
            unzip
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-openblas
            mingw-w64-x86_64-hdf5
            mingw-w64-x86_64-gsl
            autoconf
            automake-wrapper
            pkg-config
            pkgfile
            tar
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-msmpi
            python

      - name: Remove packages
        run: pacman -R --noconfirm mingw-w64-x86_64-python mingw-w64-x86_64-gdb mingw-w64-x86_64-gdb-multiarch

      - uses: actions/checkout@v4

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-generic --enable-optim --enable-download --enable-maintainer-mode --enable-debug \
            --prefix="${HOME}/freefem" \
            --with-mpipath="/c/Progam Files/Microsoft MPI/Bin" \
            MPICC=mpicc MPICXX=mpicxx MPIFC=mpif90
          ./3rdparty/getall -a -o PETSc

      - name: PETSc
        run: |
          cd 3rdparty/ff-petsc
          make petsc-slepc
          cd -
          ./reconfigure

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: make install
