name: Debian Release
on:
  workflow_run:
    workflows: ['Release']
    types:
      - completed

jobs:
  debian:
    name: Debian release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: |
          sudo apt update
          sudo apt install gcc g++ gfortran m4 patch \
            git libblas-dev liblapack-dev libsuitesparse-dev \
            libhdf5-dev libgsl-dev flex bison wget cmake autoconf \
            automake autotools-dev

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-download --prefix="/usr/local"
          ./3rdparty/getall -a -o PETSc

      - name: PETSc
        run: |
          cd 3rdparty/ff-petsc
          make petsc-slepc
          cd -
          ./reconfigure

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: sudo make install

      - name: Create DEB
        id: deb
        run: |
          OS_RELEASE=$(lsb_release -r|awk '{print $2}')
          VERSION=$(grep AC_INIT configure.ac | cut -d"," -f2 | cut -d"[" -f2 | cut -d"]" -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          DEB_FOLDER=freefem-${VERSION}-amd64-${OS_RELEASE}
          DEB_NAME=FreeFEM-${VERSION}-amd64-${OS_RELEASE}.deb
          echo "file=$DEB_NAME" >> $GITHUB_OUTPUT
          mkdir -p "$DEB_FOLDER/DEBIAN"
          touch "$DEB_FOLDER/DEBIAN/control"
          {
            echo "Package: freefem";
            echo "Version: $VERSION";
            echo "Section: custom";
            echo "Architecture: amd64";
            echo "Depends: libc6 (>= 2.31), g++ (>= 9.3), gcc (>= 9.3), gfortran (>= 9.3), libgsl-dev (>=2.5), libhdf5-dev (>=1.10.4), liblapack-dev (>= 3.9), libopenmpi-dev (>=4.0.3) ,freeglut3-dev (>= 2.8.1)";
            echo "Maintainer: FreeFEM, Frédéric Hecht <frederic.hecht@sorbonne-universite.fr>";
            echo "Description: FreeFEM, Finite Element Language software";
            echo "Homepage: https://freefem.org";
          } >> "$DEB_FOLDER/DEBIAN/control"
          mkdir -p "$DEB_FOLDER/usr/local/share/FreeFEM"
          mkdir -p "$DEB_FOLDER/usr/local/bin"
          mkdir -p "$DEB_FOLDER/usr/local/lib/ff++"
          mkdir -p "$DEB_FOLDER/usr/share/doc/freefem"

          cp -r "/usr/local/lib/ff++/$VERSION" "$DEB_FOLDER/usr/local/lib/ff++/$VERSION"
          cp -r "/usr/local/ff-petsc/" "$DEB_FOLDER/usr/local/ff-petsc"
          cp -r "/usr/local/share/FreeFEM/$VERSION" "$DEB_FOLDER/usr/local/share/FreeFEM/$VERSION"
          cp -r "/usr/local/bin/FreeFem++" "$DEB_FOLDER/usr/local/bin/FreeFem++"
          cp -r "/usr/local/bin/FreeFem++-mpi" "$DEB_FOLDER/usr/local/bin/FreeFem++-mpi"
          cp -r "/usr/local/bin/FreeFem++-nw" "$DEB_FOLDER/usr/local/bin/FreeFem++-nw"
          cp -r "/usr/local/bin/bamg" "$DEB_FOLDER/usr/local/bin/bamg"
          cp -r "/usr/local/bin/cvmsh2" "$DEB_FOLDER/usr/local/bin/cvmsh2"
          cp -r "/usr/local/bin/ff-c++" "$DEB_FOLDER/usr/local/bin/ff-c++"
          cp -r "/usr/local/bin/ff-get-dep" "$DEB_FOLDER/usr/local/bin/ff-get-dep"
          cp -r "/usr/local/bin/ff-mpirun" "$DEB_FOLDER/usr/local/bin/ff-mpirun"
          cp -r "/usr/local/bin/ff-pkg-download" "$DEB_FOLDER/usr/local/bin/ff-pkg-download"
          cp -r "/usr/local/bin/ffglut" "$DEB_FOLDER/usr/local/bin/ffglut"
          cp -r "/usr/local/bin/ffmaster" "$DEB_FOLDER/usr/local/bin/ffmaster"
          cp -r "/usr/local/bin/ffmedit" "$DEB_FOLDER/usr/local/bin/ffmedit"
          cp AUTHORS "$DEB_FOLDER/usr/share/doc/freefem/AUTHOR"
          cp README.md "$DEB_FOLDER/usr/share/doc/freefem/README.md"

          dpkg-deb --build "$DEB_FOLDER/"
          mv "$DEB_FOLDER.deb" "$DEB_NAME"

      - name: Upload release
        uses: AButler/upload-release-assets@v2.0.x
        with:
          files: ${{ steps.deb.outputs.file }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: v${{ steps.deb.outputs.number }}
