name: Release Debian
on:
  workflow_run:
    workflows: ['Release']
    types:
      - completed

jobs:
  debian:
    name: DEB release
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: |
          sudo apt update
          sudo apt install gcc g++ gfortran m4 patch \
            git libblas-dev liblapack-dev libsuitesparse-dev \
            libhdf5-dev libgsl-dev flex bison wget cmake autoconf \
            automake autotools-dev freeglut3-dev

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-optim --enable-generic --enable-download
          ./3rdparty/getall -a

      - name: PETSc
        run: |
          cd 3rdparty/ff-petsc
          make petsc-slepc SUDO=sudo
          cd -
          ./reconfigure

      - name: Build
        run: make -j2

      - name: Check
        continue-on-error: true
        run: make check

      - name: Install
        run: sudo make install

      - name: Create DEB
        id: deb
        run: |
          OS_RELEASE=$(lsb_release -r | awk '{print $2}')
          VERSION=$(grep AC_INIT configure.ac | cut -d"," -f2 | cut -d"[" -f2 | cut -d"]" -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          DEB_FOLDER=freefem-${VERSION}-amd64-ubuntu${OS_RELEASE}
          DEB_NAME=FreeFEM-${VERSION}-amd64-ubuntu${OS_RELEASE}.deb
          echo "file=$DEB_NAME" >> $GITHUB_OUTPUT

          ./etc/actions/release/linux/create_deb.sh "$VERSION" "$DEB_FOLDER" "$DEB_NAME"

      - name: Upload release
        uses: AButler/upload-release-assets@v2.0.x
        with:
          files: ${{ steps.deb.outputs.file }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: v${{ steps.deb.outputs.version }}-testActions
