name: Release
on:
  push:
    branches:
      - master
      - feature-github-actions

jobs:
  create:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Version
        id: version
        run: |
          VERSION=$(grep AC_INIT configure.ac | cut -d"," -f2 | cut -d"[" -f2 | cut -d"]" -f1)
          echo "number=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release
        continue-on-error: true
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: FreeFEM v${{ steps.version.outputs.number }}-testActions
          tag_name: v${{ steps.version.outputs.number }}-testActions
          body: '**Warning**: this is an automatic release. If you encounter some trouble with packages, post a message in the [forum](https://community.freefem.org)'
          draft: false
          prerelease: true
